Improving CMakeLists
GPUOpen-Tools/compressonator pull request #262
Opened 2023-07-12 19:42 UTC by bekorn

Issue: https://github.com/GPUOpen-Tools/compressonator/issues/261

Major Changes
- Makes cmake -DOPTION_BUILD_*=ON/OFF arguments have an effect

Minor Changes
- Improves the readability and utilization of CMake
- [TODO] Updaes documentation
This page https://compressonator.readthedocs.io/en/latest/build_from_source/build_instructions.html

2023-08-17 15:08 UTC, bekorn commented
Sorry that I didn't explain myself. I'm not familiar with the workflow of open source contribution. That is why I created a pull request "template", waiting for approval. As this had become a non-template, should I take it as approval? Is my solution doable?

Also, I don't think that I can pick the defaults by myself since I don't know the user base or common use case of the project. I will need your guidance on that.

2023-08-17 17:10 UTC, denislevesqueAMD commented
@bekorn I will be taking a look at this and let you know if I spot anything that should be changed

2023-08-21 18:26 UTC, denislevesqueAMD requested changes
I still need to download your changes on my local machine and test it, but I have some initial comments on the pull request.

2023-08-21 20:23 UTC, denislevesqueAMD commented on external/CMakeLists.txt
> +if (OPTION_BUILD_OPENCV)
This line is incorrect. The option is named `OPTION_CMP_OPENCV`.

2023-08-23 15:38 UTC, denislevesqueAMD commented
@NPCompress This pull request should be closed. I made a new pull request, #267, that fixes the issue more thoroughly.

2023-08-23 15:49 UTC, NPCompress commented
@bekorn Thank you for submission #262, with the help of @denislevesqueAMD a new pull request #267 with your changes and updates will be merged and this one will be closed.
We encourage you and others to continue to request other pull request to better serve our community members. Thanks again for your contribution.

2023-08-23 15:49 UTC, closed without merging